### ISSUE TITLE
Criar o CI exemplo

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/template-role-ansible#1]
Nesse CI tem que ter:

- [ ] Linter
- [ ] Ferramenta externa de validação de QA

Links de sugestões de ferramentas externas de validação de QA:

- https://www.codeac.io/

**Comment by glenonmateus** [comment]
Tenho interesse em participar dessa issue

seria um ótimo aprendizado já que nunca trabalhei com CI

**Comment by edsoncelio** [comment]
https://github.com/marketplace/actions/ansible-lint
